### PR TITLE
feat: atlogger timestamps

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

- Added an internal opts bitmask to the atlogger
  - Added a bit for logging timestamps; defaults to on
- Added unix timestamps to the prefix, accurate to nanoseconds (on some platforms this will be rounded to ms)

**- How I did it**

**- How to verify it**

CleanShot 2024-05-31 at 18 25 15@2x

**- Description for the changelog**
feat: atlogger timestamps

### CODE REVIEW

**Comment by gkc** [comment]
Can it be output in iso8601 format?

**Comment by xavierchanth** [comment]
Will reformat to match dart: `2024-06-03 11:44:40.560387`

**Comment by xavierchanth** [comment]
New format: 
```
 [DEBG] 2024-06-03 16:19:54.79565000 | sshnpd | Received message of type: 1
 [DEBG] 2024-06-03 16:19:54.79569000 | sshnpd | Notification value received: 11770
 [DEBG] 2024-06-03 16:19:54.79575000 | sshnpd | Waiting for next monitor thread message
 [DEBG] 2024-06-03 16:19:57.154622000 | atclient_monitor | Read nothing from the monitor
 ```

**Comment by xavierchanth** [comment]
@gkc how is that? I can truncate to ms if you want, but the clock_gettime function provides seconds & nano seconds

**Comment by gkc** [comment]
> @gkc how is that? I can truncate to ms if you want, but the clock_gettime function provides seconds & nano seconds

Looks great - I would truncate to microseconds

**Review by JeremyTubongbanua — DISMISSED** [review]

**Review by gkc — DISMISSED** [review]

**Review by JeremyTubongbanua — DISMISSED** [review]

**Comment by xavierchanth** [comment]
I noticed a mistake with alignment... leading 0's on the milliseconds are missing

**Comment by xavierchanth** [comment]
CleanShot 2024-06-04 at 14 39 08@2x

**Review by JeremyTubongbanua — APPROVED** [review]

**Pull request merged**
