### PR TITLE
feat: atclient_get_selfkey

### LINKED ISSUE #132: at_c: atclient_get_selfkey

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
closes #132 

**- What I did**
- Implemented atclient get operation `atclient_get_selfkey`

**- How to verify it**

Manual test conducted, can be found in comments section

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
Will wait on #137 to be merged before opening this pull request

**Comment by JeremyTubongbanua** [comment]
Making the self key in dart

```dart
import 'package:args/args.dart';
import 'package:at_client/at_client.dart';
import 'package:at_utils/at_utils.dart';
import 'package:dart_playground/util.dart';

Future<void> main(List<String> arguments) async {
  AtSignLogger.root_level = 'SEVERE';
  // get atsign argument from ArgsParser
  final ArgParser argsParser = ArgParser();
  argsParser.addOption('atsign',
      abbr: 'a', help: 'Owner of key', mandatory: true);
  argsParser.addOption('name',
      abbr: 'k',
      help: 'Name of the AtKey',
      mandatory: false,
      defaultsTo: 'test');
  argsParser.addOption('value',
      abbr: 'v',
      help: 'Value',
      mandatory: false,
      defaultsTo: 'some encrypted value !!! 123');
  argsParser.addOption('namespace',
      abbr: 'n',
      help: 'Namespace',
      mandatory: false,
      defaultsTo: 'dart_playground');

  final ArgResults argResults;
  try {
    argResults = argsParser.parse(arguments);
  } catch (e) {
    print(argsParser.usage);
    return;
  }

  final String atSign = argResults['atsign'];
  final String atKeyName = argResults['name'];
  final String atKeyValue = argResults['value'];
  final String namespace = argResults['namespace'];

  final AtClient atClient = await onboard(atSign);

  AtKey atKey = AtKey()
        ..key = atKeyName
        ..sharedBy = atSign
        ..namespace = namespace // default namespace
      ;

  Metadata metadata = Metadata()
        ..ttl = 1000*60*60*24*7 // 7 days
        ..ccd = true
        ..ttr = 1000 * 1 * 60 // 1 minute
        ..isEncrypted = true
      ;

  atKey.metadata = metadata;

  print('Putting ${atKey.toString()} with value $atKeyValue');

  bool success = await atClient.put(atKey, atKeyValue, putRequestOptions: PutRequestOptions()..useRemoteAtServer=true);
  if(success) {
    print('Success');
  } else {
    print('Failed');
  }

  atClient.syncService.sync();
}

```

image

**Comment by JeremyTubongbanua** [comment]
Getting the self key in C

```c
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <atlogger/atlogger.h>
#include <atclient/metadata.h>
#include <atclient/constants.h>
#include <atclient/atclient.h>
#include <atclient/atkey.h>
#include <atclient/atsign.h>

// publickey

#define TAG "Debug"

// #define ATSIGN "@jeremy_0"
#define ATSIGN "@soccer0"
#define ATKEYS_FILE_PATH "/Users/jeremytubongbanua/.atsign/keys/@soccer0_key.atKeys"

int main()
{
    int ret = 1;

    atclient_atlogger_set_logging_level(ATLOGGER_LOGGING_LEVEL_DEBUG);

    const size_t valuelen = 1024;
    atclient_atstr value;
    atclient_atstr_init(&value, valuelen);

    atclient_connection root_conn;
    atclient_connection_init(&root_conn);
    atclient_connection_connect(&root_conn, "root.atsign.org", 64);

    atclient atclient;
    atclient_init(&atclient);

    atclient_atsign atsign;
    atclient_atsign_init(&atsign, ATSIGN);

    atclient_atkey atkey;
    atclient_atkey_init(&atkey);

    atclient_atkeys atkeys;
    atclient_atkeys_init(&atkeys);
    atclient_atkeys_populate_from_path(&atkeys, ATKEYS_FILE_PATH);

    atclient_atstr atkeystr;
    atclient_atstr_init(&atkeystr, ATCLIENT_ATKEY_FULL_LEN);

    if((ret = atclient_pkam_authenticate(&atclient, &root_conn, atkeys, atsign.atsign, strlen(atsign.atsign))) != 0) {
        atclient_atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "Failed to authenticate\n");
        goto exit;
    } else {
        atclient_atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_DEBUG, "Authenticated\n");
    }
    atclient.atkeys = atkeys;
    atclient.atsign = atsign;

    if((ret = atclient_atkey_create_selfkey(&atkey, "test", strlen("test"), atsign.atsign, strlen(atsign.atsign), "dart_playground", strlen("dart_playground"))) != 0) {
        atclient_atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "Failed to create public key\n");
        goto exit;
    } else {
        atclient_atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_DEBUG, "Created self key\n");
    }

    if((ret = atclient_atkey_to_string(atkey, atkeystr.str, atkeystr.len, &atkeystr.olen)) != 0) {
        atclient_atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "Failed to convert to string\n");
        goto exit;
    }

    atclient_atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_DEBUG, "atkeystr.str (%lu): \"%.*s\"\n", atkeystr.olen, (int) atkeystr.olen, atkeystr.str);


    ret = atclient_get_selfkey(&atclient, &atkey, value.str, value.len, &(value.olen));
    if(ret != 0) {
        atclient_atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "Failed to get self key");
        goto exit;
    }

    atclient_atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_INFO, "value.str (%lu): \"%.*s\"\n", value.olen, (int) value.olen, value.str);


    ret = 0;
    goto exit;
exit: {
    atclient_atstr_free(&value);
    atclient_atkey_free(&atkey);
    atclient_atkeys_free(&atkeys);
    atclient_atstr_free(&atkeystr);
    atclient_atsign_free(&atsign);
    atclient_free(&atclient);
    return ret;
}
}

```

image

**Comment by JeremyTubongbanua** [comment]
@realvarx @XavierChanth Above is proof of a manual test

I have applied the optimization changes that we learned from the public key PR in #137 #136 

I think this is ready to merge

**Review by realvarx — APPROVED** [review]
LGTM

**Pull request merged**
