### PR TITLE
style: Adopt a clang format config

### PR DESCRIPTION
**Pull request by xavierchanth**
**- What I did**

- I was originally trying to keep the style guidelines from changing too significantly, while trying to keep true to our typical Dart / Google style guidelines.
- I still ended up with a ton of formatting changes in every file...
- So I settled on LLVM with line length 120 to keep the rules simple.

**- How I did it**

**- How to verify it**

**- Description for the changelog**
style: Adopt a clang format config

### CODE REVIEW

**Comment by xavierchanth** [comment]
This is a really big diff, but it is just straight up formatting (and the .clang-format file). If we want to go with a Microsoft base instead I can raise another PR.

**Review by gkc — APPROVED** [review]

**Review by cpswan — APPROVED** [review]

**Review by realvarx — APPROVED** [review]

**Comment by JeremyTubongbanua** [comment]
Is there any documentation (or tool) @XavierChanth so I (and other developers) can adopt this style and remain consistent?

**Comment by xavierchanth** [comment]
> Is there any documentation (or tool) @XavierChanth so I (and other developers) can adopt this style and remain consistent?

Yes, the default settings in vscode are "file" - fallback to "Visual Studio":
CleanShot 2024-02-14 at 12 53 28@2x

Now that we have a .clang-format file, vscode should just pick up the new formatting rules.

**Comment by xavierchanth** [comment]
Also @JeremyTubongbanua `clang-format -i \<path>` for example:

`clang-format -i src/*.c` and `clang-format -i include/**/*.h` in the context of our repos

Normally clang-format, like sed, will output the changes to stdout. `-i` tells clang-format to do it in-place.

**Pull request merged**
