### PR TITLE
docs: NEW atauth/README.md and atcommons/README.md, and updated maintainers list

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
**- What I did**
- Added atauth/README.md
- Added atcommons/README.md
- Updated maintainers section of ./README.md
- Added `build/` to the git ignore so that it ignores ALL build folders in any subdirectory in the entire repo.

**- How I did it**
- With hands

**- How to verify it**
- The documentation I added are instructions I tested myself

**- Description for the changelog**
docs: NEW atauth/README.md and atcommons/README.md, and updated maintainers list

### CODE REVIEW

**Review by cpswan — APPROVED** [review]
Do we need to update the CHANGELOG?

**Comment by JeremyTubongbanua** [comment]
> Do we need to update the CHANGELOG?

We do not have a CHANGELOG file in at_c yet

**Comment by cpswan** [comment]
@JeremyTubongbanua there's https://github.com/atsign-foundation/at_c/blob/trunk/packages/atclient/CHANGELOG.md

**Comment by JeremyTubongbanua** [comment]
> @JeremyTubongbanua there's https://github.com/atsign-foundation/at_c/blob/trunk/packages/atclient/CHANGELOG.md

I see

I assume that CHANGELOG is only regarding atclient changes and I don't think `atclient` uses any features from the `atcommons` package or `atauth` package; so to answer your question, I don't think we need to update the changelog.

On another note,

Should we make a global CHANGELOG.md or and/or a CHANGELOG.md for each package (atcommons, atauth, atchops, atlogger)? These packages don't have their own version.h yet either.

**Comment by xavierchanth** [comment]
As of my next pr, atclient will depend on atcommons, and both atchops and atclient had breaking changes, so both will be updated by me in the same pr.

**Pull request merged**
