### PR TITLE
fix: free() major bug in `atchops/` and `atclient/`

### LINKED ISSUE #46: at_c: free() major bug
It is possible for free() executions to occur in most functions when the variable was never allocated.

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
closes #46 

**- What I did**

- fixed free() major bug in `atchops/` package
- fixed free() major bug in `atclient/` package
- Also added some frees() to some functions that were not freeing variables originally

**- How I did it**

- moved all initialization to the top so that all variables exist in case of an error where they are then freed.

**- How to verify it**

running REPL:

image

**- Description for the changelog**

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
REPL is broken, sorry, putting back to draft

**Comment by xavierchanth** [comment]
@JeremyTubongbanua @realvarx FWIW, I'm not sure the "goto exit" pattern is better for managing memory at this point:
```c
int main(int argc, char **argv) {
  sshnpd_params *params = malloc(sizeof(sshnpd_params));

  // Load default values before parsing from argv
  apply_default_values_to_params(params);
  if (parse_params(params, argc, (const char **)argv) != 0) {
    free(params);
    return 1;
  }

  char* some_other_pointer = malloc(10);
  if(some_other_operation_that_can_error(some_other_pointer) != 0) {
    free(some_other_pointer);
    free(params);
    return 1;
  }

  // ...

  free(some_other_pointer);
  free(params);
  return 0;
}
```

While very verbose, this pattern makes it clean what memory should be cleaned up and when.

**Comment by JeremyTubongbanua** [comment]
> @JeremyTubongbanua @realvarx FWIW, I'm not sure the "goto exit" pattern is better for managing memory at this point:
> 
> ```c
> int main(int argc, char **argv) {
>   sshnpd_params *params = malloc(sizeof(sshnpd_params));
> 
>   // Load default values before parsing from argv
>   apply_default_values_to_params(params);
>   if (parse_params(params, argc, (const char **)argv) != 0) {
>     free(params);
>     return 1;
>   }
> 
>   char* some_other_pointer = malloc(10);
>   if(some_other_operation_that_can_error(some_other_pointer) != 0) {
>     free(some_other_pointer);
>     free(params);
>     return 1;
>   }
> 
>   // ...
> 
>   free(some_other_pointer);
>   free(params);
>   return 0;
> }
> ```
> 
> While very verbose, this pattern makes it clean what memory should be cleaned up and when.

Yeah, that's a good point. Your way is more efficient, but might be harder to refactor in the long run.

This PR fixes the major breaking bug for now though. We shouldn't run into malloc errors if an error occurs

**Comment by xavierchanth** [comment]
> Yeah, that's a good point. Your way is more efficient, but might be harder to refactor in the long run.
> 
> This PR fixes the major breaking bug for now though. We shouldn't run into malloc errors if an error occurs

I think it really depends on how many memory allocations were made, and what the function is doing.

**Comment by JeremyTubongbanua** [comment]
I would also argue that this makes the code look very nice. For example:

```c
int atchops_rsa_encrypt(atchops_rsakey_publickey publickey, const unsigned char *plaintext, const unsigned long plaintextlen, unsigned char *ciphertextbase64, const unsigned long ciphertextbase64len, unsigned long *ciphertextbase64olen)
{
    int ret = 1;

    mbedtls_rsa_context rsa;
    mbedtls_rsa_init(&rsa);

    mbedtls_entropy_context entropy_ctx;
    mbedtls_entropy_init(&entropy_ctx);

    mbedtls_ctr_drbg_context ctr_drbg_ctx;
    mbedtls_ctr_drbg_init(&ctr_drbg_ctx);

    const unsigned long outputlen = 256; // 256 bytes is the result of an RSA
    unsigned char *output = malloc(sizeof(unsigned char) * outputlen);
    memset(output, 0, outputlen);

    // 1. rsa encrypt the plain text
    ret = mbedtls_rsa_import_raw(&rsa, publickey.n.value, publickey.n.len, NULL, -1, NULL, -1, NULL, -1, publickey.e.value, publickey.e.len);
    if (ret != 0)
    {
        goto exit;
    }

    ret = mbedtls_rsa_check_pubkey(&rsa);
    if (ret != 0)
    {
        goto exit;
    }

    ret = mbedtls_rsa_complete(&rsa);
    if (ret != 0)
    {
        goto exit;
    }

    ret = mbedtls_ctr_drbg_seed(&ctr_drbg_ctx, mbedtls_entropy_func, &entropy_ctx, NULL, 0);
    if (ret != 0)
    {
        goto exit;
    }

    ret = mbedtls_rsa_pkcs1_encrypt(&rsa, mbedtls_ctr_drbg_random, &ctr_drbg_ctx, plaintextlen, plaintext, output);
    if (ret != 0)
    {
        goto exit;
    }

    ret = atchops_base64_encode(output, outputlen, ciphertextbase64, ciphertextbase64len, ciphertextbase64olen);
    if (ret != 0)
    {
        goto exit;
    }

    goto exit;

exit:
{
    mbedtls_rsa_free(&rsa);
    mbedtls_ctr_drbg_free(&ctr_drbg_ctx);
    mbedtls_entropy_free(&entropy_ctx);
    free(output);
    return ret;
}
}
```

**Comment by xavierchanth** [comment]
> I would also argue that this makes the code look very nice. For example:
> 
> ```c
> int atchops_rsa_encrypt(atchops_rsakey_publickey publickey, const unsigned char *plaintext, const unsigned long plaintextlen, unsigned char *ciphertextbase64, const unsigned long ciphertextbase64len, unsigned long *ciphertextbase64olen)
> {
>     int ret = 1;
> 
>     mbedtls_rsa_context rsa;
>     mbedtls_rsa_init(&rsa);
> 
>     mbedtls_entropy_context entropy_ctx;
>     mbedtls_entropy_init(&entropy_ctx);
> 
>     mbedtls_ctr_drbg_context ctr_drbg_ctx;
>     mbedtls_ctr_drbg_init(&ctr_drbg_ctx);
> 
>     const unsigned long outputlen = 256; // 256 bytes is the result of an RSA
>     unsigned char *output = malloc(sizeof(unsigned char) * outputlen);
>     memset(output, 0, outputlen);
> 
>     // 1. rsa encrypt the plain text
>     ret = mbedtls_rsa_import_raw(&rsa, publickey.n.value, publickey.n.len, NULL, -1, NULL, -1, NULL, -1, publickey.e.value, publickey.e.len);
>     if (ret != 0)
>     {
>         goto exit;
>     }
> 
>     ret = mbedtls_rsa_check_pubkey(&rsa);
>     if (ret != 0)
>     {
>         goto exit;
>     }
> 
>     ret = mbedtls_rsa_complete(&rsa);
>     if (ret != 0)
>     {
>         goto exit;
>     }
> 
>     ret = mbedtls_ctr_drbg_seed(&ctr_drbg_ctx, mbedtls_entropy_func, &entropy_ctx, NULL, 0);
>     if (ret != 0)
>     {
>         goto exit;
>     }
> 
>     ret = mbedtls_rsa_pkcs1_encrypt(&rsa, mbedtls_ctr_drbg_random, &ctr_drbg_ctx, plaintextlen, plaintext, output);
>     if (ret != 0)
>     {
>         goto exit;
>     }
> 
>     ret = atchops_base64_encode(output, outputlen, ciphertextbase64, ciphertextbase64len, ciphertextbase64olen);
>     if (ret != 0)
>     {
>         goto exit;
>     }
> 
>     goto exit;
> 
> exit:
> {
>     mbedtls_rsa_free(&rsa);
>     mbedtls_ctr_drbg_free(&ctr_drbg_ctx);
>     mbedtls_entropy_free(&entropy_ctx);
>     free(output);
>     return ret;
> }
> }
> ```

Yeah, this is a good pattern for this kind of task

**Comment by JeremyTubongbanua** [comment]
@XavierChanth Would it be okay to merge for now since optimization is not our goal and this PR fixes malloc crashing?

**Review by xavierchanth — APPROVED** [review]

**Pull request merged**
