### PR TITLE
refactor: remove `atclient_atsign`, `atclient_atstr`, refactor a bunch of function signatures

### LINKED ISSUE #127: at_c: atkey.c initializedfields
atkey.c has lots of atclient_atstrs which malloc pre-defined buffer sizes at the very start, which is not good memory management.

This ticket's capacity will estimate the work to:
- implement initializedfields in atclient_atstr
- malloc the correct size when it needs to be malloc'd
- refactor all code that uses atkeys within atkey.c and outside of atkey.c to use new implementation

### LINKED ISSUE #128: at_c: atkeys.c initializedfields
Similar to #127

### LINKED ISSUE #129: at_c: atkeysfile.c initializedfields
Similar to #127

### LINKED ISSUE #145: at_c: remove isHidden from metadata.c and all uses
In correspondence with the Dart SDK, https://github.com/atsign-foundation/at_client_sdk/issues/1562, they are deprecating isHidden, so it is best to remove it altogether while the C SDK is still in early stages.

This ticket's sprint points will measure the work of:

- [ ] Remove isHidden from metadata.c/.h
- [ ] Remove isHidden from atkey.c
- [ ] And anywhere else it is used, such as `examples/` ?

### LINKED ISSUE #153: at_c: remove atkey_type and replace it with a policy function that infers atkeytype given atclient_atkey & atclient
image

atkey.h

AtKey struct

@XavierChanth had some comments about this in #151

### LINKED ISSUE #154: at_c: rename atkey.name to atkey.key in atkey struct (atkey.h) to be consistent with dart
@XavierChanth had a comment on this in #151

### LINKED ISSUE #172: at_c: `atclient_get_public_encryption_key` should return a string
`int atclient_get_public_encryption_key(atclient *ctx, atclient_connection *root_conn, const atclient_atsign *atsign,
                                       char **public_encryption_key)`

Function should allocate string to hold public encryption key (null terminated string)

### LINKED ISSUE #226: at_c: atclient_get should not be responsible for creating shared encryption keypair if it doesn't exist
Remove `create_new` bool from the function signature of `atclient_get_sharedkey`

### LINKED ISSUE #235: at_c: atclient_delete should return *commitid

### LINKED ISSUE #247: at_c: handle malloc == NULL
If a malicious sender sent a large notification, monitor_read would allocate memory for it and could run out of memory and crash the device

Give monitor_read a max buffer length so that the caller can provide monitor_read with a proper buffer length to hold the value that it is expecting from the receiver.

### LINKED ISSUE #263: at_c: base64 optimization in atclient_put
Apply principles from https://github.com/atsign-foundation/at_c/issues/249 to optimize buffer sizes in this function.

Applying this will promote better memory usage

### LINKED ISSUE #267: at_c: base64 optimization in atclient_pkam_authenticate and atclient_monitor_pkam_authenticate
Apply principles from https://github.com/atsign-foundation/at_c/issues/249 to optimize buffer sizes in this function.

Applying this will promote better memory usage

### LINKED ISSUE #317: at_c: uniformly make all setters return `int` even if it explicitly returns 0
## Issue At Hand

Some functions return `void` and `int`

This is because the `void` functions do not require `malloc`, and therefore, is impossible to return any error codes, they always succeed.

The `int` functions require a `int` error code to return because it is possible for `malloc` to fail.

## Proposed Solution

Change the `void` functions to return `int`, but always return `0`.

This is my desired solution to keep everything uniform.

For example, somebody may want to automate the setting of metadata, they can write a `typedef` that returns `int` always, or something like that.

## Appendix

```h
void atclient_atkey_metadata_set_ispublic(atclient_atkey_metadata *metadata, const bool ispublic);
void atclient_atkey_metadata_set_ishidden(atclient_atkey_metadata *metadata, const bool ishidden);
void atclient_atkey_metadata_set_iscached(atclient_atkey_metadata *metadata, const bool iscached);
void atclient_atkey_metadata_set_ttl(atclient_atkey_metadata *metadata, const long ttl);
void atclient_atkey_metadata_set_ttb(atclient_atkey_metadata *metadata, const long ttb);
void atclient_atkey_metadata_set_ttr(atclient_atkey_metadata *metadata, const long ttr);
void atclient_atkey_metadata_set_ccd(atclient_atkey_metadata *metadata, const bool ccd);
void atclient_atkey_metadata_set_isbinary(atclient_atkey_metadata *metadata, const bool isbinary);
void atclient_atkey_metadata_set_isencrypted(atclient_atkey_metadata *metadata, const bool isencrypted);
int atclient_atkey_metadata_set_datasignature(atclient_atkey_metadata *metadata, const char *datasignature,
                                              const size_t datasignaturelen);
int atclient_atkey_metadata_set_sharedkeystatus(atclient_atkey_metadata *metadata, const char *sharedkeystatus,
                                                const size_t sharedkeystatuslen);
int atclient_atkey_metadata_set_sharedkeyenc(atclient_atkey_metadata *metadata, const char *sharedkeyenc,
                                             const size_t sharedkeyenclen);
int atclient_atkey_metadata_set_pubkeyhash(atclient_atkey_metadata *metadata, const char *pubkeyhash,
                                           const size_t pubkeyhashlen);
int atclient_atkey_metadata_set_pubkeyalgo(atclient_atkey_metadata *metadata, const char *pubkeyalgo,
                                           const size_t pubkeyalgolen);
int atclient_atkey_metadata_set_encoding(atclient_atkey_metadata *metadata, const char *encoding,
                                         const size_t encodinglen);
int atclient_atkey_metadata_set_enckeyname(atclient_atkey_metadata *metadata, const char *enckeyname,
                                           const size_t enckeynamelen);
int atclient_atkey_metadata_set_encalgo(atclient_atkey_metadata *metadata, const char *encalgo,
                                        const size_t encalgolen);
int atclient_atkey_metadata_set_ivnonce(atclient_atkey_metadata *metadata, const char *ivnonce,
                                        const size_t ivnoncelen);
int atclient_atkey_metadata_set_skeenckeyname(atclient_atkey_metadata *metadata, const char *skeenckeyname,
                                              const size_t skeenckeynamelen);
int atclient_atkey_metadata_set_skeencalgo(atclient_atkey_metadata *metadata, const char *skeencalgo,
                                           const size_t skeencalgolen);
```

### LINKED ISSUE #335: at_c: atclient_atkey_metadata_to_protocol_str should return char * as opposed to populating a buffer
Change implementation of 

`int atclient_atkey_metadata_to_protocol_str(const atclient_atkey_metadata *metadata, char *metadatastr, const size_t metadatastrsize, size_t *metadatastrlen);`

to

`int atclient_atkey_metadata_to_protocol_str(const atclient_atkey_metadata *metadata, char **metadatastr);`

### LINKED ISSUE #336: at_c: remove atclient_atsign and use char * to represent atSigns instead
We had this conversation before and just wanted to get it in writing:

We currently don't use `atclient_atsign` everywhere in our function signatures, but if we were to commit to it, it would be a lot of the following 3 lines of code:

```c
atclient_atsign atsign;
atclient_atsign_init(&atsign, "@alice");

// ...

atclient_atsign_free(&atsign);
```

Here's an image of where we use atclient_atsign right now, and it quickly becomes a tedious step to have to create an atSign object every single time.

image

I would like to propose that we eliminate the `atclient_atsign` struct completely because it is always a preliminary chore step to have to create this struct in order to pass atSign string data into a function. 

Then every time we would have to validate if an atSign string is valid, we would use a function to do the check. This is the current pattern we use in Dart.

### LINKED ISSUE #341: at_c: assume null-terminated strings in function signatures; remove strlens from function parameters
## Brief Overview

We want to remove string lengths from all function signatures and simply assume that the programmer is passing in a null-terminated string.

## Issue

Here is an example of the problem at hand:

```c
int atclient_atnotification_set_encKeyName(atclient_atnotification *notification, const char *encKeyName, const size_t encKeyNamelen);

// Frequently, this function would be called like this:

atclient_atnotification_set_encKeyName(&atnotification, "123abc", strlen("123abc"));
```

But the proposal is to remove string lengths and to always assume null-terminated strings.

```c
// So it would be called like this after this discussion is passed and approved:
atclient_atnotification_set_encKeyName(&atnotification, "123abc");
```

The reason why we want to remove string length is because it can get repetitive, tedious and an eyesore when debugging code. This function for example has at most 4 strings in its function signature which ends up being 9 function arguments. yuck!

```c
int atclient_atkey_create_publickey(atclient_atkey *atkey, const char *name, const size_t namelen, const char *sharedby,
 const size_t sharedbylen, const char *namespacestr, const size_t namespacestrlen);

// Example call

atclient_atkey_create_publickey(&atkey, "name", strlen("name"), "@jeremy", strlen("@jeremy"), "@xavier", strlen("@xavier"), "wavi", strlen("wavi");

// What we want it to be

atclient_atkey_create_publickey(&atkey, "name", "@jeremy", "@xavier", "wavi");
```

## Cons

Someone may not have the null-terminated strings on-hand and have them in something like a buffer.

For example, I could do something complicated like this

```c
char my_string[] = "name|bob|jeremy"
atclient_atkey_create_publickey(&atkey, my_string[0], 4, my_string[5], 3, my_string[9], 6); 
```

If this ticket is approved, their new implementation could be something a little more tedious like this:

```c
char my_string[] = "name|bob|jeremy";
my_string[4]='\0'
my_string[8]='\0'
my_string[15]='\0'
```

But even this doesn't work all the time. What if their string buffer was no delimited. Then they would have to do some funky string splitting.

## Alternatives

We could provide two function signatures for the caller to have the flexibility, but our code base could become quite bloated.

For Example, we could follow the strcmp/strncmp where they provide options on assuming a null-terminated string vs. providing a string length:

```c
strcmp("jeremy", "jeremy123") != 0
strncmp("jeremy", "jeremy123", 6) == 0
```

Naming could be something like this:

```c
// _s function hedaer
atclient_atkey_create_publickey_s(atclient_atkey *atkey, const char *name, const char *sharedby, const char *sharedwith, const char *namespacestr);

// _sn function header
atclient_atkey_create_publickey_sn(atclient_atkey *atkey, const char *name, const size_t namelen, const char *sharedby, const size_t sharedbylen, const char *sharedwith, const size_t sharedwithlen, const char *namespacestr, const size_t namespacestrlen);
```

### LINKED ISSUE #342: at_c: implement get_request_options, put_request_options, and delete_request_options and split apart `atclient_put` into their 3 unique variations (public, self, and shared)
## Synopsis

Currently, this is how our GET CRUD operations function signatures look like:

```
// SELFKEY
int atclient_get_selfkey(atclient *atclient, atclient_atkey *atkey, char *value, const size_t valuesize,
                         size_t *valuelen);

// PUBLICKEY
int atclient_get_publickey(atclient *atclient, atclient_atkey *atkey, char *value, const size_t valuesize,
                           size_t *valuelen, bool bypasscache);
// SHAREDKEY
int atclient_get_sharedkey(atclient *atclient, atclient_atkey *atkey, char *value, const size_t valuesize,
                           size_t *valuelen, char *shared_enc_key,
                           const bool create_new_encryption_key_shared_by_me_if_not_found);
```

Take note that SharedKey has 1 unique parameters: `shared_enc_key`, PublicKey has 1 unique parameter `bypasscache` and SelfKey has unique parameters.

(Yes the SharedKey get function has 1 unique parameter because the 2nd unique parameter bool will be removed as outlined in #226 )

## Proposal

Wrap all getters under 1 get function and future proof 

New function signature:

```
int atclient_get(atclient *atclient, atclient_atkey *atkey, char **value, atclient_get_request_options *get_request_options);
```

The `atclient_get_request_options` struct

```h
typedef struct atclient_get_request_options {
  // only applicable to publickey and sharedkey
  bool bypass_cache;

  // only applicable to sharedkey
  unsigned char *shared_enc_key
} atclient_get_request_options;
```

**Pros**
- Future proof the function signature. The function signature won't need to change when new options are added.
- One singular `get` function to get 1 of 3 key types (public, self, and shared) as opposed to 3 separate `get` functions. For example, the caller may pass in a PublicKey into the atclient_get_sharedkey function <- very possible scenario!

**Cons**
- Increased function complexity. Having all 3 kinds of keys be compatible in the `atclient_get` function complex and harder to maintain maybe in the future.

## What the Full Implementation Will Look Like

```c
// assume atclient, atkey, and value are valid variables

unsigned char shared_enc_key[32]; // pretend that this holds an AES key of 256 bits

atclient_get_request_options options;
atclient_get_request_options_init(&options);

if((ret = atclient_get_request_options_set_shared_enc_key(&options, shared_enc_key)) != 0) {
    // error handling
}

if((ret = atclient_get(&atclient, &atkey, &value, &options)) != 0) {
    // error handling
}

atclient_get_request_options_free(&options); // in the setter function, we duplicated the memory of the key and this function frees it
```

### LINKED ISSUE #346: at_c: discussion on moving `atchops_md_type` to `sha.h`
This is `constants.h` right now:

```h
#ifndef ATCHOPS_CONSTANTS_H
#define ATCHOPS_CONSTANTS_H

#define ATCHOPS_RNG_PERSONALIZATION "@atchops12345"

#include "mbedtls/md.h"

typedef enum atchops_md_type {
  ATCHOPS_MD_NONE = 0,
  ATCHOPS_MD_MD5,
  ATCHOPS_MD_RIPEMD160,
  ATCHOPS_MD_SHA1,
  ATCHOPS_MD_SHA224,
  ATCHOPS_MD_SHA256,
  ATCHOPS_MD_SHA384,
  ATCHOPS_MD_SHA512,
  ATCHOPS_MD_SHA3_224,
  ATCHOPS_MD_SHA3_256,
  ATCHOPS_MD_SHA3_384,
  ATCHOPS_MD_SHA3_512,
} atchops_md_type;

extern const mbedtls_md_type_t atchops_mbedtls_md_map[];

#endif

```

In the perspective of the person using our atSDK, If I wanted to use a variable like `ATCHOPS_MD_SHA256`, I would expect to have to do `#include<atchops/sha.h>` as opposed to `#include<atchops/constants.h>`

## Proposal

Move the MD stuff from `constants.h` to `sha.h`

### PR DESCRIPTION
**Pull request by JeremyTubongbanua**
closes #263 
closes #247
closes #267
closes #127 
closes #145 
closes #153 
closes #154 
closes #128 
closes #129 
closes #317 
closes #341 
closes #335 
closes #336
closes #172 
closes #226 
closes #235 
closes #346 
closes #342 

**- What I did**

Done as of July 12th:

- Refactored `atclient_atkey_to_string` function signature to take `char **` (originally was `char *buf, const size_t bufsize, size_t *buflen`)
- Refactored `atclient_atkey_metadata_to_protocol_str` function signature to take `char **`
- Refactored and optimized `atclient_put` to reflect changes and added comments to increase readability
- New AES CTR functions. Used to help create an optimal buffer size to be allocated to hold the result of the  encrypt/decrypt operation:
- Removed unused function in `connection.h/c`
- Removed unused function in `atkeysfile.h/c`

```
size_t atchops_aes_ctr_ciphertext_size(const size_t plaintextlen);

size_t atchops_aes_ctr_plaintext_size(const size_t ciphertextlen);
```

Done as of July 16th
- Optimized atclient_delete
- Optimized atclient_put
- Optimized atclient_pkam_authenticate
- Optimized atclient_get_atkeys
- Handle `malloc==NULL` where it was easy to handle it

Done as of July 18th
- Removed atclient_atstr from atclient_atkey and fixed atclient_atkey unit tests
- Made metadata.h/.c setters from `void` to return `int` instead as discussed in #317 
- Added `atclient_atkey_get_type` and removed `atkeytype` from `atclient_atkey` struct
- Renamed `atkey.name` to `atkey.key`

Done as of July 20th
- Finished up metadata.h/.c refactors completely, including some of the to/from jsonstr/cjson node functions
- Removed atstr from metadata
- Made all tests pass
- Removed isHidden (see #145 as to why)
- #128 - atkeys.c/.h now has _initializedfields for optimized memory management
- Removed atstr from atkeys
- Removed atstr from atkeysfile
- Deleted atstr and atbytes completely from the code base

Done as of July 22nd
- Removed atclient_atsign
- Cleaned up encryption_key_helpers.h by changing the function signatures to be more predictable
- atclient_delete now returns commit_id

Done as of July 23rd
- notify_params.h/.c (represents notification request object before sending notify command)
- atnotification.h/.c (represents a notification from monitor)

Done as of July 29th
- request_options.c/.h
- atclient_get_shared_key_request_options, atclient_get_public_key_request_options, atclient_get_self_key_request_options implementations
- atclient_delete_request_options
- atclient_put_shared_key_request_options, atclient_put_self_key_request_options, atclient_put_public_key_request_options, 
- atclient_put broken down to atclient_put_self_key, _public_key, and _shared_key
- All CRUD operations take the request_options as an optional parameter (NULLABLE)
- atclient_get_self_key takes `char **` now
- atclient_get_public_key takes `char **` now
- atclient_get_shared_key takes `char **` now
- Updated all tests accordingly
- atchops/mbedtls.h
- atclient/mbedtls.h
- atclient/cjson.h
- Removed readonly_src feature from hooks
- port in atclient_connection is now uint16_t

**- How to verify it**
- Tests still pass

**- Description for the changelog**

### CODE REVIEW

**Comment by JeremyTubongbanua** [comment]
@XavierChanth I'm having trouble understanding the logic of why the async_read check is in an `else if` statement instead of being an `if` statement on its own

image

Here is the full code

```
/*
   * 4. Send command
   */

  if ((ret = atclient_connection_send(&(atclient->atserver_connection), (unsigned char *)cmdbuffer, cmdbuffersize - 1,
                                      recv, recvsize, &recvlen)) != 0) {
    atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "atclient_connection_send: %d\n", ret);
    goto exit;
  } else if (atclient->async_read) {
    goto exit;
  }

  if (!atclient_stringutils_starts_with((char *)recv, recvlen, "data:", 5)) {
    ret = 1;
    atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "recv was \"%.*s\" and did not have prefix \"data:\"\n",
                 (int)recvlen, recv);
    goto exit;
  }

  ret = 0;
  goto exit;
exit: {
  if (!atclient->async_read) {
    free(recv);
  }
  free(atkeystr);
  free(cmdbuffer);
  return ret;
}
}
```

## My Proposal

My proposal is to make it its own if statement so that any of the sync stuff is skipped

image

**Comment by xavierchanth** [comment]
> @XavierChanth I'm having trouble understanding the logic of why the async_read check is in an `else if` statement instead of being an `if` statement on its own

In this particular case, `else if` should semantically be the same as a separate `if` since the prior `if` block has `goto exit` inside the body. Thus the `else if` and the `if` will only be reached in the same pre-existing scenarios. The first if is a guard clause, and the `else if` is a secondary guard clause.

If you to change to `if` so it is easier to follow that's fine.

**Comment by JeremyTubongbanua** [comment]
> > @XavierChanth I'm having trouble understanding the logic of why the async_read check is in an `else if` statement instead of being an `if` statement on its own
> 
> In this particular case, `else if` should semantically be the same as a separate `if` since the prior `if` block has `goto exit` inside the body. Thus the `else if` and the `if` will only be reached in the same pre-existing scenarios. The first if is a guard clause, and the `else if` is a secondary guard clause.
> 
> If you to change to `if` so it is easier to follow that's fine.

If we are in async_read, recv is not allocated and the next if statement will try reading it for `data:`

Sorry am I missing something?

```c
if ((ret = atclient_connection_send(&(atclient->atserver_connection), (unsigned char *)cmdbuffer, cmdbuffersize - 1,
                                      recv, recvsize, &recvlen)) != 0) {
    atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "atclient_connection_send: %d\n", ret);
    goto exit;
  } else if (atclient->async_read) {
    goto exit;
  }
```

**if we are using async_read**:
send command (passes) -> parse command for `data:` (error cause recv is not allocated)
send command (fails) -> goto exit;

**if we are not using async_read**:
send command (passes) -> parse command for `data:` (works cause recv is allocated)
send command (fails) -> goto exit;

**Comment by JeremyTubongbanua** [comment]
In progress:

- [x] remove atclient_atsign #336 
- [x] clean up sharedkey stuff #226 #172
- [x] separate monitor message & atnotifiaction from monitor.h, create monitor_message.h and atnotification.h
- [ ] clean up notify.c and monitor.c
- [x] separate atclient_put to 3 #342 
- [x] edit function signature buffers to expect char ** for returning the output value #342 
- [x] get/put/delete request options #342 
- [x] implement atclient_connection_write and read #345 
- [ ] #338 
- [x] move MD constants #346

**Comment by JeremyTubongbanua** [comment]
How to set notify_params now:

Before

```c
notify_params.atkey = &atkey;
notify_params.value = ATKEY_VALUE;
notify_params.operation = ATCLIENT_NOTIFY_OPERATION_UPDATE;
```

After

```c
if((ret = atclient_notify_params_set_atkey(&notify_params, &atkey)) != 0) {
    atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "Failed to set atkey\n");
    goto exit;
  }

  if((ret = atclient_notify_params_set_value(&notify_params, ATKEY_VALUE)) != 0) {
    atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "Failed to set value\n");
    goto exit;
  }

  if((ret = atclient_notify_params_set_operation(&notify_params, ATCLIENT_NOTIFY_OPERATION_UPDATE)) != 0) {
    atlogger_log(TAG, ATLOGGER_LOGGING_LEVEL_ERROR, "Failed to set operation\n");
    goto exit;
  }
```

**Comment by JeremyTubongbanua** [comment]
Things that still need to be done
- [x] separate atclient_put into atclient_put_selfkey, atclient_put_sharedkey, atclient_put_publickey
- [x] edit function signature to give back (char **) in atclient_get_selfkey
- [x] edit function signature to give back (char **) in atclient_get_sharedkey
- [x] edit function signature to give back (char **) in atclient_get_publickey
- [x] edit function signature to accept (const char *) as input as opposed to buffer and length in atclient_put_selfkey
- [x] edit function signature to accept (const char *) as input as opposed to buffer and length in atclient_put_sharedkey
- [x] edit function signature to accept (const char *) as input as opposed to buffer and length in atclient_put_publickey
- [x] implement get_request_options and use it in atclient_get*
- [x] implement put_request_options and use it in atclient_put*
- [x] implement delete_request_options and use it in atclient_delete
- [ ] #338 
- [x] atchops/mbedtls.h and atclient/cjson.h
- [x] move MD constants #346

**Comment by JeremyTubongbanua** [comment]
- [ ] separate atclient_connection_hooks into `connection_hooks.c/.h`
- [ ] implement atclient_connection_write and atclient_connection_read
- [ ] clean up connection.c/.h
- [ ] use atclient_connection_read/write in atclient_connecton_send
- [ ] use atclient_connection_read/write in atclient_notify (and clean up code)
- [ ] use atclient_connection_read/write in atclient_monitor (and clean up code)
- [ ] use atclient_connection_read/write in atclient_put
- [ ] use atclient_connection_read/write in atclient_get_selfkey
- [ ] use atclient_connection_read/write in atclient_get_sharedkey
- [ ] use atclient_connection_read/write in atclient_get_publickey
- [ ] use atclient_connection_read/write in atclient_pkam_authenticate
- [ ] use atclient_connection_read/write in atclient_send_heartbeat

- [ ] #338 
- [ ] atchops/mbedtls.h and atclient/cjson.h
- [ ] move MD constants #346 

- [ ] assertions in our tests
- [ ] clean up tests
- [ ] hooks tests

- [ ] rewrite at_talk to use hooks

**Review by xavierchanth — APPROVED** [review]

**Pull request merged**
